### ISSUE TITLE
쌤들 한번 돌려봐 주세요

### ISSUE THREAD

**Issue by songhune** [VHEX-LAB/VHEX-Tech-NLP#2]
지금 제 gpu버전 충돌 땜시 재설치중인데
cpu속도(있다면 gpu)로는 볼륨이 얼마나 걸리는지 병렬적으로 실험 부탁드립니다.
확인 되시면 pull request도 부탁드릴게요.

**Comment by songhune** [comment]
- [ ] 요것도 학기끝나면 확인

**Comment by gregchu1** [comment]
![20210617173222](https://user-images.githubusercontent.com/37770967/122361228-04f0d900-cf92-11eb-8a1b-342a55451846.png)
![20210617173230](https://user-images.githubusercontent.com/37770967/122361247-08846000-cf92-11eb-9b8c-510d05975173.png)

**Comment by gregchu1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [6월 3주차](https://trello.com/c/kqqXETN6/141-6%EC%9B%94-3%EC%A3%BC%EC%B0%A8)

**Comment by songhune** [comment]
내일 선생님이 설치한 pytorch버전이 cpu인지/gpu인지 확인
만약 gpu라면 cpu 버전으로 설치해 보시면 감사하겠습니다.
